<a href="https://colab.research.google.com/github/srikarreddy213/colab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(np.ndim(arr))

1


In [ ]:
import numpy as np
one = np.ones((3,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
iden=np.eye(3)
print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
ar=np.arange(0,10,2)
print(ar)

[0 2 4 6 8]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.dtype)



(2, 6)
12
int64


In [ ]:
import numpy as np
temp_data = np.array([[22,25,20],[24,26,23]])
print(temp_data)
print(temp_data.shape)
print(temp_data.size)
print(temp_data.dtype)
print(np.ndim(temp_data))

updated_temp_data = np.array([list(temp_data[0]), list(temp_data[1]), [21, 23, 22]])
print(updated_temp_data)

sensor_error_flags = np.zeros((2,3))
print(sensor_error_flags)
greenhouse_identity = np.eye(3,3)
print(greenhouse_identity)




[[22 25 20]
 [24 26 23]]
(2, 3)
6
int64
2
[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Indexing and Slicing:
# You are working as a Data Analyst at a fruit distribution company.

# The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
# Each row represents a type of fruit.
# Each column represents a day of the week (Mon–Sun).


# Your Tasks
# Create the 2D NumPy array

# Create an array named shipments using the above data.
# Access single elements (Indexing):
# Get the number of Apples shipped on Wednesday.
# Get the number of Oranges shipped on Sunday.
# Access multiple elements (Slicing):
# Extract all the weekday shipments (Mon–Fri) for all fruits.
# Extract only the weekend shipments (Sat & Sun).
# Extract the shipments of Apples from Wednesday to Saturday.
# Bonus (Practice thinking):
# Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.
import numpy as np
shipments = np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print("Original shipments array:")
print(shipments)

print("\nOn wednesday apples are :",shipments[0,2])
print("On Sunday orange are :",shipments[1,6])

weekday_shipments = shipments[:, 0:5]
print("\nWeekday shipments (Mon-Fri):")
print(weekday_shipments)

weekend_shipments = shipments[:, 5:7]
print("\nWeekend shipments (Sat & Sun):")
print(weekend_shipments)


apples_wed_to_sat = shipments[0, 2:6]
print("\nApple shipments from Wednesday to Saturday:")
print(apples_wed_to_sat)


shipments[0, 5] = 100
print("\nShipments array after updating Saturday Apple shipment:")
print(shipments)

Original shipments array:
[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]

On wednesday apples are : 55
On Sunday orange are : 75

Weekday shipments (Mon-Fri):
[[50 60 55 70 65]
 [40 45 50 60 55]]

Weekend shipments (Sat & Sun):
[[80 90]
 [70 75]]

Apple shipments from Wednesday to Saturday:
[55 70 65 80]

Shipments array after updating Saturday Apple shipment:
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [ ]:
import numpy as np

s = np.array([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
])

print("4-dimensional array:")
print(s)
print("\nShape of the array:", s.shape)
print("Number of dimensions:", np.ndim(s))

4-dimensional array:
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]

Shape of the array: (2, 2, 2, 2)
Number of dimensions: 4


In [ ]:
#broadcast
x=np.array([30,60,180])
y=6

print("x + y:", x+y)
print("np.sin(x):", np.sin(x))
print("np.add(x, y):", np.add(x, y))
print("np.subtract(x, y):", np.subtract(x, y))
print("np.multiply(x, y):", np.multiply(x, y))
print("np.divide(x, y):", np.divide(x, y))
print("np.power(x, y):", np.power(x, y))
print("np.mod(x, y):", np.mod(x, y))
print("np.exp(x):", np.exp(x))
print("np.log(x):", np.log(x))
print("np.log10(x):", np.log10(x))
print("np.log2(x):", np.log2(x))
print("np.expm1(x):", np.expm1(x))    # exp(x) - 1
print("np.arcsin(x):", np.arcsin(x))
print("np.arccos(x):", np.arccos(x))
print("np.arctan(x):", np.arctan(x))
print("np.degrees(x):", np.degrees(x))
print("np.radians(x):", np.radians(x))
print("np.round(x):", np.round(x))
print("np.floor(x):", np.floor(x))
print("np.ceil(x):", np.ceil(x))
print("np.trunc(x):", np.trunc(x))
print("np.min(x):", np.min(x))
print("np.max(x):", np.max(x))
print("np.mean(x):", np.mean(x))
print("np.std(x):", np.std(x))
print("np.var(x):", np.var(x))
print("np.sum(x):", np.sum(x))
print("np.prod(x):", np.prod(x))

print("np.logical_and(x, y):", np.logical_and(x, y))
print("np.logical_or(x, y):", np.logical_or(x, y))
print("np.logical_not(x):", np.logical_not(x))
print("np.logical_xor(x, y):", np.logical_xor(x, y))
print("np.greater(x, y):", np.greater(x, y))
print("np.less(x, y):", np.less(x, y))
print("np.equal(x, y):", np.equal(x, y))
print("np.not_equal(x, y):", np.not_equal(x, y))
print("np.greater_equal(x, y):", np.greater_equal(x, y))
print("np.less_equal(x, y):", np.less_equal(x, y))
print("np.bitwise_and(x, y):", np.bitwise_and(x, y))
print("np.bitwise_or(x, y):", np.bitwise_or(x, y))
print("np.bitwise_xor(x, y):", np.bitwise_xor(x, y))
print("np.invert(x):", np.invert(x))

x + y: [ 36  66 186]
np.sin(x): [-0.98803162 -0.30481062 -0.80115264]
np.add(x, y): [ 36  66 186]
np.subtract(x, y): [ 24  54 174]
np.multiply(x, y): [ 180  360 1080]
np.divide(x, y): [ 5. 10. 30.]
np.power(x, y): [     729000000    46656000000 34012224000000]
np.mod(x, y): [0 0 0]
np.exp(x): [1.06864746e+13 1.14200739e+26 1.48938420e+78]
np.log(x): [3.40119738 4.09434456 5.19295685]
np.log10(x): [1.47712125 1.77815125 2.25527251]
np.log2(x): [4.9068906 5.9068906 7.4918531]
np.expm1(x): [1.06864746e+13 1.14200739e+26 1.48938420e+78]
np.arcsin(x): [nan nan nan]
np.arccos(x): [nan nan nan]
np.arctan(x): [1.53747533 1.5541312  1.56524083]
np.degrees(x): [ 1718.87338539  3437.74677078 10313.24031235]
np.radians(x): [0.52359878 1.04719755 3.14159265]
np.round(x): [ 30  60 180]
np.floor(x): [ 30.  60. 180.]
np.ceil(x): [ 30.  60. 180.]
np.trunc(x): [ 30.  60. 180.]
np.min(x): 30
np.max(x): 180
np.mean(x): 90.0
np.std(x): 64.8074069840786
np.var(x): 4200.0
np.sum(x): 270
np.prod(x): 324000
np

/tmp/ipython-input-2504923425.py:18: RuntimeWarning: invalid value encountered in arcsin
  print("np.arcsin(x):", np.arcsin(x))
/tmp/ipython-input-2504923425.py:19: RuntimeWarning: invalid value encountered in arccos
  print("np.arccos(x):", np.arccos(x))


In [ ]:
# You are a data engineer at a renewable-energy company that runs 3 solar farms.
# Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

# Given data (raw)
# Create arrays from these values:
# production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
# Farm A panels (rows = panels, cols = hours):


# Tasks
# Create arrays
# Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
# Stack them into a single 3D array production_all of shape (3, 4, 3).
# Array attributes
# Print the .shape, .size, .dtype, and .ndim of production_all.
# Per-farm totals (arithmetic & aggregation)
# Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
# Compute mean, std, and var per farm.
# Per-hour matrix multiplication idea (matrix op)
# For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
# Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
# Broadcasting adjustments
# The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
# Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
# Compute a normalized version where you:
# subtract the per-farm mean (use broadcasting),
# divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
# Apply many ufuncs (use the ufuncs listed previously)
# Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
# Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
# Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
# Rounding: np.round, np.floor, np.ceil, np.trunc.
# Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
# Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
# Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
# Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
# Broadcast-based summary table
# Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
# Final KPIs (aggregation)
# Compute:
# overall_total (sum of all farms),
# peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
# average_per_panel across all farms.





import numpy as np

fa = np.array([[10, 12, 11], [9, 11, 10], [12, 13, 14], [8, 7, 9]])
fb = np.array([[20, 19, 21], [18, 20, 19], [22, 23, 21], [17, 18, 16]])
fc = np.array([[15, 16, 14], [14, 13, 15], [16, 17, 18], [12, 11, 13]])
production_all = np.array([fa, fb, fc])

print("Original production_all array:")
print(production_all)
print("\nShape of production_all:", production_all.shape)
print("Size of production_all:", production_all.size)
print("Data type of production_all:", production_all.dtype)
print("Number of dimensions of production_all:", production_all.ndim)

total_per_farm = np.sum(production_all, axis=(1, 2))
print("\nTotal energy production per farm:")
print(total_per_farm)

mean_per_farm = np.mean(production_all, axis=(1, 2))
std_per_farm = np.std(production_all, axis=(1, 2))
var_per_farm = np.var(production_all, axis=(1, 2))

print("\nMean energy production per farm:")
print(mean_per_farm)
print("\nStandard deviation of energy production per farm:")
print(std_per_farm)
print("\nVariance of energy production per farm:")
print(var_per_farm)

# Per-hour matrix multiplication idea (matrix op)
hour_weights = np.array([0.5, 1.0, 0.75])
weighted_per_panel = np.dot(production_all, hour_weights)
print("\nWeighted energy production per panel:")
print(weighted_per_panel)

# Broadcasting adjustments
production_all[1] = production_all[1] + 0.5
print("\nProduction_all array after adding offset to Farm B:")
print(production_all)

# Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
normalized_production = (production_all - mean_per_farm[:, np.newaxis, np.newaxis]) / std_per_farm[:, np.newaxis, np.newaxis]
print("\nNormalized production data (z-score):")
print(normalized_production)

# Apply many ufuncs
exp_normalized = np.exp(normalized_production)
expm1_normalized = np.expm1(normalized_production)
log_normalized = np.log(np.abs(normalized_production))  # Using absolute value to handle non-positive inputs
log10_normalized = np.log10(np.abs(normalized_production))
log2_normalized = np.log2(np.abs(normalized_production))

print("\nExponential family ufuncs on normalized data:")
print("np.exp:", exp_normalized.shape, exp_normalized.dtype, exp_normalized[0, 0, :])
print("np.expm1:", expm1_normalized.shape, expm1_normalized.dtype, expm1_normalized[0, 0, :])
print("np.log:", log_normalized.shape, log_normalized.dtype, log_normalized[0, 0, :])
print("np.log10:", log10_normalized.shape, log10_normalized.dtype, log10_normalized[0, 0, :])
print("np.log2:", log2_normalized.shape, log2_normalized.dtype, log2_normalized[0, 0, :])

sin_normalized = np.sin(normalized_production)
cos_normalized = np.cos(normalized_production)
tan_normalized = np.tan(normalized_production)
arcsin_normalized = np.arcsin(np.clip(normalized_production, -1, 1)) # Clip to valid range
arccos_normalized = np.arccos(np.clip(normalized_production, -1, 1)) # Clip to valid range
arctan_normalized = np.arctan(normalized_production)

print("\nTrigonometric ufuncs on normalized data:")
print("np.sin:", sin_normalized.shape, sin_normalized.dtype, sin_normalized[0, 0, :])
print("np.cos:", cos_normalized.shape, cos_normalized.dtype, cos_normalized[0, 0, :])
print("np.tan:", tan_normalized.shape, tan_normalized.dtype, tan_normalized[0, 0, :])
print("np.arcsin:", arcsin_normalized.shape, arcsin_normalized.dtype, arcsin_normalized[0, 0, :])
print("np.arccos:", arccos_normalized.shape, arccos_normalized.dtype, arccos_normalized[0, 0, :])
print("np.arctan:", arctan_normalized.shape, arctan_normalized.dtype, arctan_normalized[0, 0, :])

degrees_normalized = np.degrees(normalized_production)
radians_production = np.radians(production_all)

print("\nDegree and Radian conversions:")
print("np.degrees(normalized):", degrees_normalized.shape, degrees_normalized.dtype, degrees_normalized[0, 0, :])
print("np.radians(production_all):", radians_production.shape, radians_production.dtype, radians_production[0, 0, :])

round_normalized = np.round(normalized_production)
floor_normalized = np.floor(normalized_production)
ceil_normalized = np.ceil(normalized_production)
trunc_normalized = np.trunc(normalized_production)

print("\nRounding ufuncs on normalized data:")
print("np.round:", round_normalized.shape, round_normalized.dtype, round_normalized[0, 0, :])
print("np.floor:", floor_normalized.shape, floor_normalized.dtype, floor_normalized[0, 0, :])
print("np.ceil:", ceil_normalized.shape, ceil_normalized.dtype, ceil_normalized[0, 0, :])
print("np.trunc:", trunc_normalized.shape, trunc_normalized.dtype, trunc_normalized[0, 0, :])

# Comparison & logical ufuncs
high_output = production_all > 20
print("\nBoolean mask for high output (> 20):")
print(high_output)

# Example logical operations (need another mask, e.g., for even hours)
# Creating a dummy mask for demonstration
even_hours_mask = np.zeros_like(production_all, dtype=bool)
even_hours_mask[:, :, ::2] = True # Assuming hours 0 and 2 are "even"
print("\nDummy mask for even hours:")
print(even_hours_mask)

logical_and_mask = np.logical_and(high_output, even_hours_mask)
logical_or_mask = np.logical_or(high_output, even_hours_mask)
logical_not_mask = np.logical_not(high_output)
logical_xor_mask = np.logical_xor(high_output, even_hours_mask)

print("\nLogical ufuncs on masks:")
print("np.logical_and(high_output, even_hours_mask):", logical_and_mask.shape, logical_and_mask.dtype, logical_and_mask[0, 0, :])
print("np.logical_or(high_output, even_hours_mask):", logical_or_mask.shape, logical_or_mask.dtype, logical_or_mask[0, 0, :])
print("np.logical_not(high_output):", logical_not_mask.shape, logical_not_mask.dtype, logical_not_mask[0, 0, :])
print("np.logical_xor(high_output, even_hours_mask):", logical_xor_mask.shape, logical_xor_mask.dtype, logical_xor_mask[0, 0, :])

greater_equal_20 = np.greater_equal(production_all, 20)
less_10 = np.less(production_all, 10)

print("\nComparison ufuncs:")
print("np.greater_equal(production_all, 20):", greater_equal_20.shape, greater_equal_20.dtype, greater_equal_20[0, 0, :])
print("np.less(production_all, 10):", less_10.shape, less_10.dtype, less_10[0, 0, :])

# Bitwise ufuncs (on integer arrays)
alerts = np.array([[[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
                   [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
                   [[1,0,1],[0,0,1],[1,1,0],[0,1,0]]]) # Replicate for 3 farms
print("\nAlerts array (integer):")
print(alerts)

bitwise_and_alerts = np.bitwise_and(production_all.astype(int), alerts) # Ensure both are integers
bitwise_or_alerts = np.bitwise_or(production_all.astype(int), alerts)
invert_alerts = np.invert(alerts)

print("\nBitwise ufuncs on integer arrays:")
print("np.bitwise_and(production_all, alerts):", bitwise_and_alerts.shape, bitwise_and_alerts.dtype, bitwise_and_alerts[0, 0, :])
print("np.bitwise_or(production_all, alerts):", bitwise_or_alerts.shape, bitwise_or_alerts.dtype, bitwise_or_alerts[0, 0, :])
print("np.invert(alerts):", invert_alerts.shape, invert_alerts.dtype, invert_alerts[0, 0, :])

# Arithmetic ufuncs again
add_result = np.add(production_all, 1)
subtract_result = np.subtract(production_all, 1)
multiply_result = np.multiply(production_all, 2)
divide_result = np.divide(production_all, 2)
power_result = np.power(production_all, 2)
mod_result = np.mod(production_all, 2)

print("\nArithmetic ufuncs:")
print("np.add(production_all, 1):", add_result.shape, add_result.dtype, add_result[0, 0, :])
print("np.subtract(production_all, 1):", subtract_result.shape, subtract_result.dtype, subtract_result[0, 0, :])
print("np.multiply(production_all, 2):", multiply_result.shape, multiply_result.dtype, multiply_result[0, 0, :])
print("np.divide(production_all, 2):", divide_result.shape, divide_result.dtype, divide_result[0, 0, :])
print("np.power(production_all, 2):", power_result.shape, power_result.dtype, power_result[0, 0, :])
print("np.mod(production_all, 2):", mod_result.shape, mod_result.dtype, mod_result[0, 0, :])

# Aggregations over ufunc outputs
sum_exp_normalized = np.sum(exp_normalized)
mean_sin_normalized = np.mean(sin_normalized)

print("\nAggregations over ufunc outputs:")
print("np.sum(np.exp(normalized_production)):", sum_exp_normalized)
print("np.mean(np.sin(normalized_production)):", mean_sin_normalized)

panel_totals_per_farm = np.sum(production_all, axis=2)
print("\nPanel totals per farm (sum across hours):")
print(panel_totals_per_farm)

needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("\nNeeds maintenance (any panel total < 40 per farm):")
print(needs_maintenance)

# Final KPIs (aggregation)
overall_total = np.sum(production_all)
print("\nOverall total production:", overall_total)

peak_hour_value = np.max(production_all)
peak_hour_index = np.argmax(production_all)
peak_farm, peak_panel, peak_hour = np.unravel_index(peak_hour_index, production_all.shape)

print("\nPeak hour value:", peak_hour_value)
print("Peak production occurred at Farm:", peak_farm, ", Panel:", peak_panel, ", Hour:", peak_hour)

average_per_panel_across_all_farms = np.mean(production_all, axis=(0, 2))
print("\nAverage production per panel across all farms:")
print(average_per_panel_across_all_farms)

Original production_all array:
[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]

Shape of production_all: (3, 4, 3)
Size of production_all: 36
Data type of production_all: int64
Number of dimensions of production_all: 3

Total energy production per farm:
[126 234 174]

Mean energy production per farm:
[10.5 19.5 14.5]

Standard deviation of energy production per farm:
[1.97905701 1.97905701 1.97905701]

Variance of energy production per farm:
[3.91666667 3.91666667 3.91666667]

Weighted energy production per panel:
[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]

Production_all array after adding offset to Farm B:
[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]

Normalized production data (z-score):
[[[-0.25264558  0.75793673  0.

In [ ]:
#stacking and spliting

fa = np.array([[10, 12, 11], [9, 11, 10], [12, 13, 14], [8, 7, 9]])
fb = np.array([[20, 19, 21], [18, 20, 19], [22, 23, 21], [17, 18, 16]])
c=np.vstack((fa,fb))
print(c)
print(np.hstack((fa,fb)))
print(fa[fa>10])


[[10 12 11]
 [ 9 11 10]
 [12 13 14]
 [ 8  7  9]
 [20 19 21]
 [18 20 19]
 [22 23 21]
 [17 18 16]]
[[10 12 11 20 19 21]
 [ 9 11 10 18 20 19]
 [12 13 14 22 23 21]
 [ 8  7  9 17 18 16]]
[12 11 11 12 13 14]


In [ ]:
import numpy as np
a=np.arange(1,51)
print(a)
ran = np.random.random((3, 3))
ran1 = np.random.random((3, 3))
print(ran)
print(a.shape)
print(a.size)
print(a.dtype)
print(np.ndim(a))





[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[0.23554587 0.80963121 0.6320234 ]
 [0.75983514 0.57410616 0.41435094]
 [0.50940209 0.30486849 0.11446345]]
(50,)
50
int64
1


In [ ]:
import numpy as np
a=np.arange(1,51)
print(a)
ran = np.random.random((3, 3))
ran1 = np.random.random((3, 3))
print(ran)
print(a.shape)
print(a.size)
print(a.dtype)
print(np.ndim(a))

print(a+5)
print(np.dot(ran,ran1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[0.82783526 0.10056157 0.64924089]
 [0.65608262 0.72922398 0.01666632]
 [0.79986218 0.9263828  0.48321168]]
(50,)
50
int64
1
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55]
[[0.13502694 0.86769044 0.80978082]
 [0.21711766 0.99832757 0.65203612]
 [0.30953819 1.33085433 1.05069739]]


In [ ]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)
print("first row :",arr[0])
print("last column :",arr[:,4])
subarr = arr[:3, :2]
print(subarr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
first row : [1 2 3 4 5]
last column : [ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [ ]:
arr1=np.array(np.random.randint(1,101,10))
print(arr1)
print("max value",np.max(arr1))
print("min value",np.min(arr1))
print("mean value",np.mean(arr1))
print("median value",np.median(arr1))
print("std value",np.std(arr1))


[11 65 15  8 11 24  1 93 67 57]
max value 93
min value 1
mean value 35.2
median value 19.5
std value 30.54439392098


In [ ]:
a2=np.arange(1,13).reshape(3,4)
print(a2)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

matrix = np.ones((3, 3))
print("Original matrix:\n", matrix)

arr = np.array([1, 2, 3])

result = matrix + arr
print("\nAfter adding [1, 2, 3] to each row:\n", result)


In [ ]:
import numpy as np

a = np.random.randint(1, 51, 10)
b = a[a % 5 == 0]
print(a)
print(b)


In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.dot(a, b)
print(c)


In [ ]:
import numpy as np

a = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12],
              [13, 14, 15, 16]])

diag = a[np.arange(4), np.arange(4)]
print(diag)


[ 1  6 11 16]
